/* empty css                      */(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function r(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(o){if(o.ep)return;o.ep=!0;const s=r(o);fetch(o.href,s)}})();let l=null;const u="https://your-energy.b.goit.study/api/quote";async function f(){try{const e=await fetch(u);if(!e.ok)throw new Error("Failed to fetch quote");const t=await e.json();y(t)}catch(e){console.error(e)}}f();function y(e){const t=document.querySelector(".quote-text"),r=document.querySelector(".quote-author");t.textContent=e.quote,r.textContent=`-${e.author}`}let a="Muscles";const p=document.querySelector(".filters");p.addEventListener("click",e=>{const t=e.target.closest(".filter-tab");t&&(a=t.dataset.filter,g(),d(a))});function g(){document.querySelectorAll(".filter-tab").forEach(t=>{const r=t.dataset.filter===a;t.classList.toggle("is-active",r)})}const m="https://your-energy.b.goit.study/api/filters";async function d(e){try{const t=await fetch(`${m}?filter=${e}`);if(!t.ok)throw new Error("Failed to fetch filters");const r=await t.json();h(r.results)}catch(t){console.error(t)}}function h(e){const t=document.querySelector(".filters-content");if(t){if(!Array.isArray(e)){console.error("renderFilters expected array, got:",e);return}t.innerHTML=e.map(r=>`
        <button 
          class="filter-item" 
          data-filter="${r.filter}"
          data-value="${r.name}"
        >
          ${r.name}
        </button>
      `).join("")}}d(a);const E=document.querySelector(".filters-content");E.addEventListener("click",e=>{const t=e.target.closest(".filter-item");if(!t)return;const r=t.dataset.value;x(a,r)});const q="https://your-energy.b.goit.study/api/exercises";async function x(e,t){try{const r=new URLSearchParams;e==="Muscles"&&r.append("muscles",t),e==="Body parts"&&r.append("bodypart",t),e==="Equipment"&&r.append("equipment",t),r.append("page",1),r.append("limit",6);const c=await fetch(`${q}?${r.toString()}`);if(!c.ok)throw new Error("Failed to fetch exercises");const o=await c.json();b(o.results)}catch(r){console.error(r)}}function b(e){const t=document.querySelector(".exercises-list");t&&(t.innerHTML=e.map(r=>`
        <li class="exercise-card">
          <img src="${r.gifUrl}" alt="${r.name}" width="200" />
          <h3>${r.name}</h3>
          <p>Target: ${r.target}</p>
          <p>Rating: ${r.rating}</p>
          <button class="start-btn" data-id="${r._id}">
            Start
          </button>
        </li>
      `).join(""))}const w=document.querySelector(".exercises-list"),n=document.querySelector(".modal");w.addEventListener("click",e=>{const t=e.target.closest(".start-btn");if(!t)return;const r=t.dataset.id;S(r)});async function S(e){try{l=e;const t=await fetch(`https://your-energy.b.goit.study/api/exercises/${e}`);if(!t.ok)throw new Error("Failed to fetch exercise");const r=await t.json();L(r),$()}catch(t){console.error(t)}}function L(e){n.querySelector(".modal-gif").src=e.gifUrl,n.querySelector(".modal-gif").alt=e.name,n.querySelector(".modal-title").textContent=e.name,n.querySelector(".modal-description").textContent=e.description,n.querySelector(".modal-bodypart").textContent=e.bodyPart,n.querySelector(".modal-equipment").textContent=e.equipment,n.querySelector(".modal-target").textContent=e.target,n.querySelector(".modal-rating").textContent=e.rating}function $(){n.classList.remove("is-hidden")}function C(){n.classList.add("is-hidden")}n.addEventListener("click",e=>{(e.target.classList.contains("modal")||e.target.classList.contains("modal-close"))&&C()});async function v(e,t){try{const r=await fetch(`https://your-energy.b.goit.study/api/exercises/${e}/rating`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(t)});if(!r.ok)throw new Error("Failed to send rating");return await r.json()}catch(r){console.error(r)}}const F=document.querySelector(".rating-form");F.addEventListener("submit",async e=>{e.preventDefault();const t=new FormData(e.target),r={rate:Number(t.get("rate")),email:t.get("email"),review:t.get("review")||""},c=await v(l,r);c&&(n.querySelector(".modal-rating").textContent=c.rating,e.target.reset())});
//# sourceMappingURL=index.js.map
