/* empty css                      */(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function r(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(o){if(o.ep)return;o.ep=!0;const n=r(o);fetch(o.href,n)}})();const u="https://your-energy.b.goit.study/api/quote";async function d(){try{const e=await fetch(u);if(!e.ok)throw new Error("Failed to fetch quote");const t=await e.json();f(t)}catch(e){console.error(e)}}d();function f(e){const t=document.querySelector(".quote-text"),r=document.querySelector(".quote-author");t.textContent=e.quote,r.textContent=`-${e.author}`}let i="Muscles";const p=document.querySelector(".filters");p.addEventListener("click",e=>{const t=e.target.closest(".filter-tab");t&&(i=t.dataset.filter,y(),l(i))});function y(){document.querySelectorAll(".filter-tab").forEach(t=>{const r=t.dataset.filter===i;t.classList.toggle("is-active",r)})}const h="https://your-energy.b.goit.study/api/filters";async function l(e){try{const t=await fetch(`${h}?filter=${e}`);if(!t.ok)throw new Error("Failed to fetch filters");const r=await t.json();g(r.results)}catch(t){console.error(t)}}function g(e){const t=document.querySelector(".filters-content");if(t){if(!Array.isArray(e)){console.error("renderFilters expected array, got:",e);return}t.innerHTML=e.map(r=>`
        <button 
          class="filter-item" 
          data-filter="${r.filter}"
          data-value="${r.name}"
        >
          ${r.name}
        </button>
      `).join("")}}l(i);const m=document.querySelector(".filters-content");m.addEventListener("click",e=>{const t=e.target.closest(".filter-item");if(!t)return;const r=t.dataset.value;E(i,r)});const q="https://your-energy.b.goit.study/api/exercises";async function E(e,t){try{const r=new URLSearchParams;e==="Muscles"&&r.append("muscles",t),e==="Body parts"&&r.append("bodypart",t),e==="Equipment"&&r.append("equipment",t),r.append("page",1),r.append("limit",6);const c=await fetch(`${q}?${r.toString()}`);if(!c.ok)throw new Error("Failed to fetch exercises");const o=await c.json();S(o.results)}catch(r){console.error(r)}}function S(e){const t=document.querySelector(".exercises-list");t&&(t.innerHTML=e.map(r=>`
        <li class="exercise-card">
          <img src="${r.gifUrl}" alt="${r.name}" width="200" />
          <h3>${r.name}</h3>
          <p>Target: ${r.target}</p>
          <p>Rating: ${r.rating}</p>
          <button class="start-btn" data-id="${r._id}">
            Start
          </button>
        </li>
      `).join(""))}const b=document.querySelector(".exercises-list"),s=document.querySelector(".modal");b.addEventListener("click",e=>{const t=e.target.closest(".start-btn");if(!t)return;const r=t.dataset.id;x(r)});async function x(e){try{const t=await fetch(`https://your-energy.b.goit.study/api/exercises/${e}`);if(!t.ok)throw new Error("Failed to fetch exercise");const r=await t.json();L(r),w()}catch(t){console.error(t)}}function L(e){s.querySelector(".modal-gif").src=e.gifUrl,s.querySelector(".modal-gif").alt=e.name,s.querySelector(".modal-title").textContent=e.name,s.querySelector(".modal-description").textContent=e.description,s.querySelector(".modal-bodypart").textContent=e.bodyPart,s.querySelector(".modal-equipment").textContent=e.equipment,s.querySelector(".modal-target").textContent=e.target,s.querySelector(".modal-rating").textContent=e.rating}function w(){s.classList.remove("is-hidden")}function $(){s.classList.add("is-hidden")}s.addEventListener("click",e=>{(e.target.classList.contains("modal")||e.target.classList.contains("modal-close"))&&$()});
//# sourceMappingURL=index.js.map
