/* empty css                      */(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const a of o)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function r(o){const a={};return o.integrity&&(a.integrity=o.integrity),o.referrerPolicy&&(a.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?a.credentials="include":o.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(o){if(o.ep)return;o.ep=!0;const a=r(o);fetch(o.href,a)}})();let u=null,i=null;const p="https://your-energy.b.goit.study/api/quote";async function m(){try{const t=await fetch(p);if(!t.ok)throw new Error("Failed to fetch quote");const e=await t.json();g(e)}catch(t){console.error(t)}}m();function g(t){const e=document.querySelector(".quote-text"),r=document.querySelector(".quote-author");e.textContent=t.quote,r.textContent=`-${t.author}`}let c="Muscles";const h=document.querySelector(".filters");h.addEventListener("click",t=>{const e=t.target.closest(".filter-tab");e&&(c=e.dataset.filter,w(),f(c))});function w(){document.querySelectorAll(".filter-tab").forEach(e=>{const r=e.dataset.filter===c;e.classList.toggle("is-active",r)})}const E="https://your-energy.b.goit.study/api/filters";async function f(t){try{const e=await fetch(`${E}?filter=${t}`);if(!e.ok)throw new Error("Failed to fetch filters");const r=await e.json();q(r.results)}catch(e){console.error(e)}}function q(t){const e=document.querySelector(".filters-content");if(e){if(!Array.isArray(t)){console.error("renderFilters expected array, got:",t);return}e.innerHTML=t.map(r=>`
        <button 
          class="filter-item" 
          data-filter="${r.filter}"
          data-value="${r.name}"
        >
          ${r.name}
        </button>
      `).join("")}}f(c);const b=document.querySelector(".filters-content");b.addEventListener("click",t=>{const e=t.target.closest(".filter-item");if(!e)return;const r=e.dataset.value;i=e.dataset.value,S(c,r)});const y="https://your-energy.b.goit.study/api/exercises";async function S(t,e){try{const r=new URLSearchParams;t==="Muscles"&&r.append("muscles",e),t==="Body parts"&&r.append("bodypart",e),t==="Equipment"&&r.append("equipment",e),r.append("page",1),r.append("limit",6);const s=await fetch(`${y}?${r.toString()}`);if(!s.ok)throw new Error("Failed to fetch exercises");const o=await s.json();d(o.results)}catch(r){console.error(r)}}function d(t){const e=document.querySelector(".exercises-list");e&&(e.innerHTML=t.map(r=>`
        <li class="exercise-card">
          <img src="${r.gifUrl}" alt="${r.name}" width="200" />
          <h3>${r.name}</h3>
          <p>Target: ${r.target}</p>
          <p>Rating: ${r.rating}</p>
          <button class="start-btn" data-id="${r._id}">
            Start
          </button>
        </li>
      `).join(""))}const x=document.querySelector(".exercises-list"),n=document.querySelector(".modal");x.addEventListener("click",t=>{const e=t.target.closest(".start-btn");if(!e)return;const r=e.dataset.id;L(r)});async function L(t){try{u=t;const e=await fetch(`https://your-energy.b.goit.study/api/exercises/${t}`);if(!e.ok)throw new Error("Failed to fetch exercise");const r=await e.json();$(r),F()}catch(e){console.error(e)}}function $(t){n.querySelector(".modal-gif").src=t.gifUrl,n.querySelector(".modal-gif").alt=t.name,n.querySelector(".modal-title").textContent=t.name,n.querySelector(".modal-description").textContent=t.description,n.querySelector(".modal-bodypart").textContent=t.bodyPart,n.querySelector(".modal-equipment").textContent=t.equipment,n.querySelector(".modal-target").textContent=t.target,n.querySelector(".modal-rating").textContent=t.rating}function F(){n.classList.remove("is-hidden")}function v(){n.classList.add("is-hidden")}n.addEventListener("click",t=>{(t.target.classList.contains("modal")||t.target.classList.contains("modal-close"))&&v()});async function C(t,e){try{const r=await fetch(`https://your-energy.b.goit.study/api/exercises/${t}/rating`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(e)});if(!r.ok)throw new Error("Failed to send rating");return await r.json()}catch(r){console.error(r)}}const j=document.querySelector(".rating-form");j.addEventListener("submit",async t=>{t.preventDefault();const e=new FormData(t.target),r={rate:Number(e.get("rate")),email:e.get("email"),review:e.get("review")||""},s=await C(u,r);s&&(n.querySelector(".modal-rating").textContent=s.rating,t.target.reset())});const M=document.querySelector(".search-form");M.addEventListener("submit",t=>{t.preventDefault();const r=new FormData(t.target).get("keyword").trim();r&&R(r)});async function R(t){if(!i){console.warn("Select a filter category before searching");return}try{const e=new URLSearchParams({keyword:t,page:1,limit:6});c==="Muscles"&&e.append("muscles",i),c==="Body parts"&&e.append("bodypart",i),c==="Equipment"&&e.append("equipment",i);const r=await fetch(`${y}?${e.toString()}`);if(r.status===409){d([]);return}if(!r.ok)throw new Error("Failed to fetch exercises by keyword");const s=await r.json();d(s.results)}catch(e){console.error(e)}}
//# sourceMappingURL=index.js.map
